//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Регистрация.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medcarti
    {
        public int ID_medcarti { get; set; }
        public Nullable<int> ID_pacienta { get; set; }
        public string FIO_pacienta { get; set; }
        public string FIO_sotrudnika { get; set; }
        public string Diagnoz { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
